version: '3.3'
services:
  db1:
    image: mysql:8.0.32
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'SP9imKy1d33EFN7ER3fg'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'SP9imKy1d33EFN7ER3fg'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '8000:3306'
    expose:
      # Opens port 3306 on the container
      - '8000'
      # Where our data will be persisted
    volumes:
      - ./my-db:/var/lib/mysql

# # Names our volume
# volumes:
#   my-db: